extends: eslint-recommended
env:
  browser: true
  es6: true
  jquery: true
  node: true
parser: babel-eslint
parserOptions:
  ecmaFeatures:
    jsx: true
root: true
plugins:
  - react
rules:
  react/jsx-uses-react: error
  react/jsx-uses-vars: error
